---
title: "generate_datasets_for_CVPASapp"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{generate_datasets_for_CVPASapp}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(CVhelp)
library(dplyr)
# library(DT)

# shiny::actionButton("refresh_ann_data_butt","refresh")
# shiny::observeEvent(input$refresh_ann_data_butt,{
#   
#   })
# summary of Head of Old River (HOR) barrier summary by year
HOR_bar_ann_data <- data.frame(CVhelp::get_HOR_barrier_data(dt_rng = c("2011-01-01", "2024-12-31")) %>% 
             dplyr::mutate(year=format(date,"%Y"),
                           Year=as.numeric(year)) %>%
               dplyr::group_by(Year) %>% 
             dplyr::summarize(barrier_days=sum(barrierTF),
                              barrier=ifelse(sum(barrierTF)>0,"In","Out"))) #%>%
  
WYT_data <- CVhelp:::get_WYT_data(dt_rng=c("2011-01-01","2024-12-31")) #%>% rename(year=Year)# local access

ann_HORbar_WYT_data <- HOR_bar_ann_data %>% dplyr::left_join(WYT_data,by="Year")

# CVhelp::w



```
